### ISSUE TITLE
Compiling for x86 in VS2019

### ISSUE THREAD

**Issue by barriopedro** [slater1/Kdl.NetStandard#2]
Since the Nuget package is only for x64 and i have a dpendency with a x86 dll.
How should i recompile for x86? i'm having problems with orocos_kinematics_dynamics compilation with a LINK1112 error

**Comment by slater1** [comment]
Thanks for reaching out. I just pushed a few commits which add support for x86. I skipped it before because my use case didn't require x64. 

I've also added an x86 package. https://www.nuget.org/packages/Kdl.NetStandard.x86/
Completely untested. Let me know how it goes!

**Comment by barriopedro** [comment]
It works ! Many thanks.
but i had to copy manually Kdl.NetStandard.dll from nuget package to output directory.
 I cannot remember if with x64 version I had to do the same.

**Comment by slater1** [comment]
Good, glad it works! And I found a copy is necessary if you use an old-style csproj.
